default_roles:
  # core packages
  - pacman
  - paru
  # removed packages
  - dunst
  - vim
  # install packages
  - 7zip
  - act
  - ags-hyprpanel-git
  - ark
  - bat
  - betterdiscordctl
  - blockbench
  - btop
  - catppuccin-cursors-mocha
  - cliphist
  - discord
  - docker
  - docker-compose
  - dolphin
  - fastfetch
  - gamemode
  - ghostty
  - gimp
  - git
  - github-cli
  - grim
  - heroic-games-launcher-bin
  - htop
  - hyprcursor
  - hyprland
  - hyprpaper
  - hyprpolkitagent
  - hyprshot
  - iwd
  - jdk17-temurin
  - jdk21-temurin
  - jekyll
  - kitty
  - kvantum
  - nano
  - neovim
  - nfs-utils
  - openssh
  - os-prober
  - partitionmanager
  - pavucontrol
  - plymouth
  - polkit-kde-agent
  - pre-commit
  - prismlauncher
  - python313
  - qdirstat-bin
  - qt5-wayland
  - qt6-wayland
  - rofi
  - rubygems
  - slurp
  - smartmontools
  - sshfs
  - sshpass
  - steam
  - steam-rom-manager-bin
  - telegram-desktop
  - uv
  - uwsm
  - visual-studio-code-bin
  - vlc
  - waterfox-bin
  - wget
  - wine
  - wireless_tools
  - wofi
  - xdg-desktop-portal-hyprland
  - xdg-utils
  - zsh