default_roles:
  # core packages
  - pacman
  - paru
  # install packages
  - 7zip
  - act
  - ark
  - bat
  - blockbench
  - btop
  - cliphist
  - discord
  - docker
  - dolphin
  - fastfetch
  - gamemode
  - gimp
  - git
  - grub
  - heroic-games-launcher
  - hypr
  - iwd
  - jdk-temurin
  - jekyll
  - kvantum
  - nano
  - neovim
  - nfs-utils
  - partitionmanager
  - pavucontrol
  - plymouth
  - prismlauncher
  - python
  - qdirstat
  - qt-wayland
  - rofi
  - rubygems
  - smartmontools
  - ssh
  - steam
  - telegram
  - uwsm
  - vlc
  - vscode
  - waterfox
  - wget
  - wine
  - wireless_tools
  - xdg-utils
  - zsh
  - ghostty