---
- name: hypr | run hyprland tasks
  ansible.builtin.include_tasks: hyprland.yml

- name: hypr | run hyprcursor tasks
  ansible.builtin.include_tasks: hyprcursor.yml

- name: hypr | run hyprpanel tasks
  ansible.builtin.include_tasks: hyprpanel.yml

- name: hypr | run hyprpaper tasks
  ansible.builtin.include_tasks: hyprpaper.yml

- name: hypr | run hyprpolkit tasks
  ansible.builtin.include_tasks: hyprpolkit.yml

- name: hypr | run hyprshot tasks
  ansible.builtin.include_tasks: hyprshot.yml