---
- name: python | ensure python (latest) installed
  kewlfft.aur.aur:
    name: python
    state: present
    use: paru
  become_user: aur_builder

- name: python | ensure python313 installed
  kewlfft.aur.aur:
    name: python313
    state: present
    use: paru
  become_user: aur_builder

- name: python | ensure uv installed
  kewlfft.aur.aur:
    name: uv
    state: present
    use: paru
  become_user: aur_builder