---
- name: pacman | Enable multilib (section)
  ansible.builtin.lineinfile:
    path: /etc/pacman.conf
    regexp: '^#\[multilib\]'
    line: '[multilib]'
    state: present
    backup: yes

- name: pacman | Enable multilib (Include)
  ansible.builtin.lineinfile:
    path: /etc/pacman.conf
    regexp: '^#?Include = /etc/pacman.d/mirrorlist'
    line: 'Include = /etc/pacman.d/mirrorlist'
    insertafter: '^\[multilib\]'
    state: present

- name: pacman | Enable 'Color'
  ansible.builtin.lineinfile:
    path: /etc/pacman.conf
    regexp: '^#Color'
    line: 'Color'
    state: present

- name: pacman | Enable 'ILoveCandy'
  ansible.builtin.lineinfile:
    path: /etc/pacman.conf
    regexp: '^#ILoveCandy'
    line: 'ILoveCandy'
    state: present

- name: pacman | Update package cache
  ansible.builtin.pacman:
    update_cache: yes