---
- name: docker | ensure docker installed
  kewlfft.aur.aur:
    name: docker
    state: present
    use: paru
  become_user: aur_builder

- name: docker | ensure docker-compose installed
  kewlfft.aur.aur:
    name: docker-compose
    state: present
    use: paru
  become_user: aur_builder
